//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Error404_Web.Models.Error404_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CTOrder = new HashSet<CTOrder>();
        }
    
        public string MaDH { get; set; }
        public Nullable<double> TongDH { get; set; }
        public Nullable<double> TongSP { get; set; }
        public Nullable<double> TongDC { get; set; }
        public Nullable<double> TongShip { get; set; }
        public string Email { get; set; }
        public string DCID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTOrder> CTOrder { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
