//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Error404_Web.Models.Error404_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public string RateID { get; set; }
        public string RateImg { get; set; }
        public string Text { get; set; }
        public string Email { get; set; }
        public string MaSP { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
